### ISSUE TITLE
Error communicating with API: 404, message='Not Found'

### ISSUE THREAD

**Issue by marcogabriel** [LouisForaux/saur-homeassistant#2]
Thanks for the integration. I tried to set it up on a Home Assistant Docker based installation.

After setting up, I get the following error (subscription id replaced by x'es):

```
Error communicating with API: 404, message='Not Found', 
    url='https://apib2c.azure.saurclient.fr/deli/section_subscription/xxxxxxxxxxxxxxxxxx/consumptions/weekly?
    year=2024&month=12&day=22'
```

This loops within a few seconds and always fails.

Any ideas?

**Comment by LouisForaux** [comment]
Hey Marco !

The integration works with the saurclient.fr website for “connected” meters, or at least meters that are read at least once a week.
If the meter is not connected or is not French, integration will unfortunately not work.

Have a nice day!

**Comment by marcogabriel** [comment]
Hey Louis, thanks for your swift answer. AFAIK, our meter is connected (it was replaced by a connected meter a few months ago, at least that was my understanding) and it is a french meter.

DO you know if I can check that somewhere at the saurclient.fr client portal? Or how do I know that it is connected?

Thanks,
Marco

**Comment by LouisForaux** [comment]
Hey ! 
Go on that page : https://mon-espace.saurclient.fr/fr/ma-consommation
After click on "Mois" (or "Month" it depends of the language of your browser), if you see data for everydays, it should work.

Have a nice day,

**Comment by marcogabriel** [comment]
Thanks for your help. If I go to "ma consommation" I can only see a yearly summary value and there is no button or link named "mois" or "month". That explains why I can't get data out of it.

Thanks for your help.

**Comment by mathieuedet** [comment]
@marcogabriel I have exactly same behavior. It has been changed few month ago with a connected but I only have yearly consumption on website and 404 error on home assistant.

Do you have resolved the problem since your report ?
